<?php

use Illuminate\Database\Seeder;

class EstatesForTest extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Run the database seeds.
         *
         * @return void
         */

        DB::table('estates')->insert([
            [
                'name' => 'Monitor Acer',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Cadeira ABCD',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Monitor Lero Lero',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Quadro Branco',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Headset H-33',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ], [
                'name' => 'Minigame',
                'value' => rand (100, 8000),
                'label_id' => rand (),
                'categories_id' => rand (1, 2),
                'sub_categories_id' => rand (1, 10),
                'seller_id' =>  rand (1, 2),
            ]
        ]);
    }
}
